dist: bionic
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - composer update --no-interaction --prefer-dist --no-suggest

before_script:

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run
