language: php

php:
  - '7.2'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - composer update --no-interaction --prefer-dist --no-suggest

before_script:

script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run
